// WARNING: auto-generated by Makefile release target -- run 'make release' to update

package eve

const (
	Version     = "v0.9.2"
	GitCommit   = "31161ec" // the commit JUST BEFORE the release
	VersionDate = "2023-08-10 20:32" // UTC
)

