// WARNING: auto-generated by Makefile release target -- run 'make release' to update

package eve

const (
	Version     = "v0.6.3"
	GitCommit   = "3fc042f"          // the commit JUST BEFORE the release
	VersionDate = "2020-06-28 21:13" // UTC
)
