// WARNING: auto-generated by Makefile release target -- run 'make release' to update

package eve

const (
	Version = "v0.6.0"
	GitCommit = "09ec980" // the commit JUST BEFORE the release
	VersionDate = "2020-03-30 10:18" // UTC
)

